### ISSUE TITLE
ONESIGNAL_MODULE_OPTIONS Error

### ISSUE THREAD

**Issue by PazminoJose** [kvandake/onesignal-nest#29]
I´m trying to use the OneSignal service into a module but i get the next error: Nest can't resolve dependencies of the OneSignalService (?). Please make sure that the argument ONESIGNAL_MODULE_OPTIONS at index [0] is available in the NotificationSenderModule context.

My module file looks like:
import { Module } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { OneSignalModule, OneSignalService } from 'onesignal-api-client-nest';
import { NotificationSenderService } from './notification-sender.service';

@Module({
  imports: [
    &nbsp;&nbsp;&nbsp;&nbsp;OneSignalModule.forRootAsync({
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;useFactory: async (configService: ConfigService) => {
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return {
         &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; appId: configService.get('ONESIGNAL_APP_ID'),
          &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;restApiKey: configService.get('ONESIGNAL_REST_API_KEY'),
       &nbsp;&nbsp;&nbsp;&nbsp; };
     &nbsp;&nbsp;&nbsp;&nbsp; },
      &nbsp;&nbsp;&nbsp;&nbsp;inject: [ConfigService],
    &nbsp;&nbsp;&nbsp;&nbsp;}),
  ],
  providers: [
    NotificationSenderService,
    OneSignalService,
  ]
})
export class NotificationSenderModule { }

I can´t figure what is the problem

**Comment by panalgin** [comment]
Hello @BlueBird0399

Import OneSignalModule.forRootAsync in your AppModule, not in your NotificationSenderModule, that should fix it.

By the way I would suggest using official onesignal nodejs sdk here at https://github.com/OneSignal/onesignal-node-api  which is a first party implementation coming from onesignal team

Our project is a bit out of date, and I don't think there is a need for NestJS flavor of it as of now.

Thanks

**Comment by PazminoJose** [comment]
> Hello @BlueBird0399
> 
> Import OneSignalModule.forRootAsync in your AppModule, not in your NotificationSenderModule, that should fix it.
> 
> By the way I would suggest using official onesignal nodejs sdk here at https://github.com/OneSignal/onesignal-node-api which is a first party implementation coming from onesignal team
> 
> Our project is a bit out of date, and I don't think there is a need for NestJS flavor of it as of now.
> 
> Thanks

Thanks, I'll take a look at that package.
